### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by abesolberg** [jonathansmart/BayesGrowth#5]
Hi,

I'm having trouble compiling BayesGrowth. I've tried installing it with the tar.gz, using `devtools::install_github`, from cran, and downloading the code and building the package.

The error I continue get is:

 `make: *** [C:/PROGRA~1/MIE74D~1/ROPEN~1/R-40~1.2/etc/x64/Makeconf:229: RcppExports.o] Error 2
ERROR: compilation failed for package 'BayesGrowth'`

I'm using Microsoft R Open 4.0.2. I have the following packages/versions installed without issue.

    AquaticLifeHistory (1.0.5),
    bayesplot (1.7.2),
    dplyr (1.1.4),
    ggplot2 (3.4.4),
    loo (2.6.0),
    methods (4.0.2),
    Rcpp (1.0.9),
    RcppParallel (5.1.7),
    rstan (2.32.2),
    rstantools (2.3.1.1),
    stats (4.0.2),
    tibble (3.2.1),
    tidybayes (3.0.6) ,
    knitr (1.40),
    BH (1.78.0.0),
    RcppEigen (0.3.3.9.4),
    StanHeaders (2.32.2)

Thanks in advance!

**Comment by jonathansmart** [comment]
Do you have the corresponding version of rtools installed? This is needed to compile code for the package.

**Comment by abesolberg** [comment]
I have Rtools 4.0 installed.

**Comment by jonathansmart** [comment]
Ok. The package has been tested across multiple platforms but I'm not familiar with Microsoft Open R. It's likely that this requires a different config file to the other platforms which is why the package won't install. I was going to investigate this further but then found this post about Open R being discontinued (https://techcommunity.microsoft.com/t5/azure-sql-blog/microsoft-r-application-network-retirement/ba-p/3707161). If this is the case then it's unlikely that I'll be able to find a solution. Are you considering switching to R 4.3? If so this package will install without any issues.

**Comment by abesolberg** [comment]
I'm hesitant to switch. MRAN on windows increases my computational speed for a lot of matrix based packages, so I'd like to keep using it, but realizing that it's been discontinued I'll close the issue and try to find a different approach. Thanks for looking into it!
